#!/usr/bin/python3

import linecache
import os, sys

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


def copy_to_clip(argv):
	file = argv
	print(file)
	clip = ""

	line = str(linecache.getline(file, 4))
	line = line.split("\t")
	try:
		ports = str(line[1])[7:]
		ports = ports.replace(" ", "").replace("\n","")
		ports = ports.split(",")

		for port in ports:
			clip += port.split("/")[0] + ","

		clip = clip[:-1]
		print(bcolors.HEADER + "[+] " + bcolors.ENDC + clip)
		print(bcolors.HEADER + "[+] " + bcolors.ENDC + "ports copied to clipboard")
		os.system(f'echo -n {clip} | xclip')

	except Exception as e:
		print(bcolors.FAIL + "[-] " + bcolors.ENDC + "ERROR. Perhaps wrong file name.")



if __name__ == "__main__":
	if len(sys.argv) == 2:
		copy_to_clip(sys.argv[1])
	else:
		print(bcolors.WARNING + "[!] " + bcolors.ENDC + "Usage: get-ports <filename>")
